# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Dofeature"
title:              ""
description:        "Urban Computing Research Group"


# URL
url:                http://cityimage.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

empty-img: 	       images/empty.png

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
#  - name:           "home"
#    href:           "/"
#  - name:           "about"
#    href:           "/about"
  - name:           "blog"
    href:           "/blog"
  - name:           "people"
    href:           "/people"
  - name:           "publications"
    href:           "/publication"
#   - name:           "abstracts" # felipe added 230602
#     href:           "/abstracts"
  # - name:           "resources"
  #   href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
